import { ACCENTS } from "../accents";
import type { ProtocolDefinition } from "../types";

export const i2c: ProtocolDefinition = {
  id: "i2c",
  name: "I²C",
  longName: "Inter-Integrated Circuit",
  subtitle: "Two-wire addressable peripheral bus",
  layer: "Embedded Bus",
  layerId: "embedded",
  communication: "Synchronous · Multi-drop · Controller/Target",
  purpose: "Cheap, short-distance chip-to-chip communication",
  hook:
    "Two wires and an address. It connects a dozen chips on one board using only two pins of your microcontroller.",
  intro:
    "I²C is not a networking protocol and it does not sit in the TCP/IP stack. It is a board-level bus: it connects chips that are centimetres apart on the same printed circuit board. One device, the controller, drives a clock. Everyone else listens. Because each target has its own address, a single pair of wires can carry a conversation with a temperature sensor, a real-time clock, an EEPROM and an OLED display without any of them needing a dedicated pin.",
  accent: ACCENTS.i2c,

  problem: {
    headline: "A microcontroller does not have enough pins",
    detail:
      "A small MCU might have twenty usable pins, and a board might carry six peripheral chips. Wire them the obvious way — one dedicated line each for chip select, data in, data out and clock — and you have spent twenty-four pins before you have connected anything interesting. You also have a routing problem: four traces per chip crossing a crowded two-layer board, each one a place a signal can be corrupted. What is needed is a bus where the pin cost does not grow with the number of devices.",
    failures: [
      "Pin count grows with every device added — the resource runs out first",
      "Point-to-point wiring does not scale; each new chip means new traces",
      "Chips on a board do not need long-distance signalling or routing, so most of a networking stack is wasted",
      "A shared multi-drop connection needs a way to address devices, or they all collide",
      "Two devices may try to drive the same wire at once, which would mean a short circuit",
      "Peripherals differ in speed, so the bus must tolerate a slow target without stalling the whole system",
    ],
  },
  solution: {
    headline: "Two wires, addressed targets, one clock",
    concepts: [
      {
        tag: "signalling",
        title: "Open-drain, with pull-ups",
        glyph: "pullup",
        body:
          "Every device can only pull a line *low*; it can never drive it high. External resistors pull the lines up. This means two devices pulling the bus at once is harmless — the result is simply low — so a short circuit is physically impossible. It is what makes a shared bus safe.",
      },
      {
        tag: "wiring",
        title: "Two lines: SDA and SCL",
        glyph: "clock",
        body:
          "SDA carries data and SCL carries the clock, both bidirectional. The clock is always generated by the controller, which is what makes this a synchronous bus: the receiver never has to guess the sender's bit rate because it is told when to sample.",
      },
      {
        tag: "addressing",
        title: "A 7-bit address per device",
        glyph: "multidrop",
        body:
          "Every transaction begins with an address. Only the chip that recognises it responds; everyone else stays silent. 112 usable addresses on one bus, which is far more than a typical board needs.",
      },
      {
        tag: "framing",
        title: "START, STOP and repeated START",
        glyph: "handshake",
        body:
          "START and STOP are not separate wires — they are SDA changing while SCL is high, a transition that cannot occur inside valid data. This framing is what lets a receiver know when a transaction begins and ends. A repeated START begins a new transaction without releasing the bus.",
      },
      {
        tag: "flow",
        title: "Clock stretching",
        glyph: "priority",
        body:
          "A target that cannot keep up holds SCL low, and the controller waits. A simple sensor can therefore sit on a fast bus without needing a buffer, which is why I²C tolerates a wide range of device speeds on one pair of wires.",
      },
      {
        tag: "arbitration",
        title: "Arbitration without destruction",
        glyph: "arbitration",
        body:
          "Because nobody can drive a line high, two controllers that start talking at once can each detect that the bus does not match what they sent, and the loser backs off. No data is corrupted and nothing is damaged.",
      },
      {
        tag: "cost",
        title: "Almost no overhead",
        glyph: "stateless",
        body:
          "No PHY, no transceiver, no termination. Two pins, two resistors and a trace on the board. This is why I²C is on essentially every sensor, EEPROM, real-time clock and small display in existence.",
      },
    ],
  },

  mechanics: {
    headline: "How one register read works",
    framing:
      "Follow a read of two bytes from a sensor. This is the canonical I²C transaction: write the register address you want, then read it back — with a repeated START in between so the controller keeps control of the bus.",
    stack: [
      { label: "Application", sub: "read_temperature()" },
      { label: "I²C driver", sub: "register address + length", emphasis: true },
      { label: "I²C bus", sub: "SDA and SCL, open-drain", emphasis: true },
      { label: "Target chip", sub: "sensor at a fixed address" },
    ],
    steps: [
      {
        id: "idle",
        title: "Bus idle",
        summary: "Both lines are high, held there by the pull-up resistors.",
        body:
          "Nothing is driving the bus, so the resistors pull both SDA and SCL to the supply rail. Every transaction both begins and ends in this state, which is what lets a device that has lost track of the bus resynchronise.",
        facts: [
          { key: "SDA", value: "high (via pull-up)" },
          { key: "SCL", value: "high (via pull-up)" },
        ],
      },
      {
        id: "start",
        title: "START condition",
        summary: "The controller pulls SDA low while SCL is still high.",
        body:
          "This specific transition is illegal during normal data transfer, because data is only allowed to change while the clock is low. That is exactly why it works as a delimiter: it can never be mistaken for a data bit. It wakes every chip on the bus and tells them to listen for an address.",
        sequence: {
          caption: "START: SDA falls while SCL is high",
          nodes: [{ label: "Controller", sub: "drives SDA, SCL" }, { label: "Target", sub: "listens" }],
          arrows: [
            { from: 0, to: 1, label: "SDA ↓ while SCL = 1", detail: "START", tone: "accent" },
          ],
        },
      },
      {
        id: "address",
        title: "Address byte and read/write bit",
        summary: "Seven address bits, then one bit saying read or write.",
        body:
          "The controller shifts out the seven-bit address of the target it wants, most significant bit first, each bit sampled while the clock pulses. The eighth bit is the direction: 0 to write, 1 to read. Every other chip on the bus compares the address, decides it is not for them, and goes quiet.",
        facts: [
          { key: "Address width", value: "7 bits (a 10-bit form exists but is rare)" },
          { key: "Usable addresses", value: "112, after reserving the 16 special-purpose codes" },
          { key: "Direction bit", value: "0 = write, 1 = read" },
        ],
      },
      {
        id: "ack",
        title: "ACK from the target",
        summary: "The addressed target pulls SDA low for one clock.",
        body:
          "After the ninth clock the controller releases SDA. If a chip recognised its address it pulls the line low — an ACK. If nothing responds, the line stays high, which reads as NACK, and the controller learns there is no device at that address. This is the only feedback the bus provides, and it is what a bus scanner uses to enumerate connected devices.",
        facts: [
          { key: "ACK", value: "SDA = 0 during the ninth clock" },
          { key: "NACK", value: "SDA = 1 — no device, or the target refuses" },
          { key: "A byte costs", value: "8 data bits + 1 acknowledge bit" },
        ],
      },
      {
        id: "register",
        title: "Send the register address",
        summary: "Chips are register files; you address a byte inside the chip.",
        body:
          "Most I²C targets are not 'send me a byte' devices — they are banks of registers. So the controller writes the register number it wants (the WHO_AM_I register, or a temperature output register), and the target ACKs. This is the write half of a read transaction, and it establishes an internal pointer inside the chip.",
        sequence: {
          caption: "Point at a register",
          nodes: [{ label: "Controller" }, { label: "Sensor" }],
          arrows: [
            { from: 0, to: 1, label: "0x76 + W", detail: "address, direction = write", tone: "accent" },
            { from: 1, to: 0, label: "ACK", tone: "ok" },
            { from: 0, to: 1, label: "0xFA", detail: "register address", tone: "accent" },
            { from: 1, to: 0, label: "ACK", tone: "ok" },
          ],
        },
      },
      {
        id: "restart",
        title: "Repeated START",
        summary: "Keep control of the bus instead of letting it go idle.",
        body:
          "Instead of issuing a STOP and a fresh START — which would release the bus and allow another controller to seize it, changing the register pointer of an unrelated chip in between — the controller issues a repeated START. The bus is never released, the transaction stays indivisible, and the target's internal register pointer is preserved.",
        facts: [
          { key: "Without it", value: "another controller could interleave and corrupt the sequence" },
          { key: "On the wire", value: "same timing as START, with no STOP before it" },
        ],
      },
      {
        id: "read",
        title: "Read the data",
        summary: "The target transmits bytes; the controller acknowledges each one.",
        body:
          "Now the direction is read. The target drives SDA and the controller provides the clock. After each byte the controller answers: ACK to ask for another byte, NACK to say 'that is the last one.' The roles of who drives SDA and who acknowledges have swapped, and the controller still owns the clock throughout.",
        facts: [
          { key: "Controller sends", value: "ACK after each byte it wants more of" },
          { key: "Final byte", value: "answered with NACK to end the read" },
        ],
      },
      {
        id: "stop",
        title: "STOP condition",
        summary: "SDA rises while SCL is high, releasing the bus.",
        body:
          "The mirror of START. The controller lets SDA go high while the clock is high, returning the bus to idle. Every device resets its internal transaction state and waits for the next START. If a device was reset mid-transaction by a glitch, this is also how firmware recovers the bus — by clocking out nine pulses and then issuing a clean STOP.",
        sequence: {
          caption: "STOP: SDA rises while SCL is high",
          nodes: [{ label: "Controller" }, { label: "Sensor" }],
          arrows: [
            { from: 1, to: 0, label: "data byte 1", tone: "accent" },
            { from: 0, to: 1, label: "ACK", tone: "ok" },
            { from: 1, to: 0, label: "data byte 2", tone: "accent" },
            { from: 0, to: 1, label: "NACK", detail: "last byte", tone: "warn" },
            { from: 0, to: 0, label: "SDA ↑ while SCL = 1", detail: "STOP", tone: "accent" },
          ],
        },
      },
    ],
  },

  frame: {
    unit: "Transaction (address byte + data bytes)",
    overhead: "1 address byte minimum; 2 per register access in practice",
    note:
      "There is no I²C header in the TCP sense. Framing is entirely provided by START and STOP conditions on the wires, and by the acknowledge bit after every single byte.",
    rows: [
      {
        label: "Framing",
        fields: [
          {
            name: "START (S)",
            size: "condition",
            span: 1,
            tone: "accent",
            role: "SDA falls while SCL is high. Begins a transaction.",
            detail:
              "Wakes every device on the bus. Cannot occur inside valid data, so it is unambiguous by construction rather than by an escape character.",
          },
          {
            name: "Address (7 bits)",
            size: "7 bits",
            span: 2,
            tone: "accent",
            role: "Which target this transaction is for.",
            detail:
              "Send most significant bit first. Parts of the space are reserved: 0000xxx for general call, CBUS and high-speed-mode codes; 1111xxx for the 10-bit addressing form. That leaves 112 addresses for ordinary devices — and the reason many sensors ship with two or three address-selection pins, so several of the same part can coexist.",
            example: "0x76 — a common accelerometer address",
          },
          {
            name: "R/W̄",
            size: "1 bit",
            span: 1,
            tone: "ok",
            role: "Direction of the transfer that follows.",
            detail:
              "0 means the controller writes; 1 means the controller reads and the target will drive SDA. It is the eighth bit of the first byte, so address and direction always travel together.",
            example: "0 = write",
          },
          {
            name: "ACK / NACK",
            size: "1 bit",
            span: 1,
            tone: "warn",
            role: "Per-byte handshake, sent by the receiver of that byte.",
            detail:
              "Pulled low to acknowledge, left high to decline. The acknowledgment bit after the address byte is how the controller detects a missing device. The NACK after the final data byte is how it terminates a read.",
            example: "ACK",
          },
          {
            name: "STOP (P)",
            size: "condition",
            span: 1,
            tone: "accent",
            role: "SDA rises while SCL is high. Ends the transaction.",
            detail:
              "Returns the bus to idle and resets every device's transaction state. Omitted when a repeated START is used instead, so the controller keeps the bus.",
          },
        ],
      },
      {
        label: "Optional inside the data phase",
        fields: [
          {
            name: "Register Address",
            size: "1–2 bytes",
            span: 3,
            role: "Which internal register of the target to access.",
            detail:
              "Not part of the I²C specification — it is a convention that almost every real chip follows. The controller writes a register number first, so subsequent reads or writes land on the right byte inside the device. Very large devices, such as EEPROMs, use two bytes to address 64 KB or more.",
            example: "0xFA — a temperature output register",
          },
          {
            name: "Register Data",
            size: "n bytes",
            span: 3,
            role: "The payload, defined entirely by the device datasheet.",
            detail:
              "I²C specifies nothing about what a byte means, which is why the datasheet is mandatory reading. Multi-byte values in most sensors are big-endian, so a 12-bit temperature may arrive across two registers with the low nibble unused.",
            example: "0x0C, 0x80 → 25.0 °C",
          },
        ],
      },
      {
        label: "Electrical",
        fields: [
          {
            name: "SDA",
            size: "1 wire",
            span: 2,
            role: "Bidirectional data, open-drain, held high by a pull-up.",
            detail:
              "Open-drain means a device can only pull the line low. Two devices driving simultaneously therefore produce a valid low, not a short circuit — which is what makes a shared bus electrically safe and enables arbitration.",
          },
          {
            name: "SCL",
            size: "1 wire",
            span: 2,
            role: "Clock, always driven by the controller, also open-drain.",
            detail:
              "Being open-drain allows clock stretching: a target holding the line low forces the controller to wait. The maximum capacitance on the bus, not the clock rate, is usually what limits how many devices can share it.",
            example: "100 pF for standard mode",
          },
          {
            name: "Pull-up resistors",
            size: "2 resistors",
            span: 2,
            tone: "ok",
            role: "Pull both lines high when nothing is driving them.",
            detail:
              "Typical values are 4.7 kΩ at 100 kHz and 1–2 kΩ at 400 kHz and above. There is a real trade-off: too weak and the lines rise slowly at high speed, too strong and a low-level driver sinks more current than the specification allows. Bus capacitance is the deciding factor.",
            example: "4.7 kΩ to 3.3 V",
          },
          {
            name: "Ground",
            size: "1 wire",
            span: 2,
            role: "Common reference for both signals.",
            detail:
              "Because I²C is intended for chips on one board, there is no isolation and no differential signalling. Two wires plus ground is the whole physical layer.",
          },
        ],
      },
    ],
  },

  realWorld: {
    title: "A sensor hub on a drone flight controller",
    scenario:
      "One microcontroller, five peripherals, and only two pins used for all of them. This is why I²C exists — not because it is fast, but because it is cheap in pins and traces.",
    hops: [
      {
        label: "Flight controller",
        sub: "the single controller on the bus",
        facts: [
          { key: "I²C port", value: "SDA / SCL on two GPIO pins" },
          { key: "Clock", value: "400 kHz (fast mode)" },
          { key: "Pull-ups", value: "2.2 kΩ to 3.3 V" },
        ],
      },
      {
        label: "IMU — 0x68",
        sub: "accelerometer + gyroscope",
        facts: [
          { key: "Read", value: "6 bytes from 0x3B — accel X/Y/Z" },
          { key: "Rate", value: "every 1 ms for the control loop" },
          { key: "Mode", value: "highest priority — a late sample degrades flight" },
        ],
      },
      {
        label: "Barometer — 0x77",
        sub: "altitude reference",
        facts: [
          { key: "Read", value: "pressure + temperature, converted to altitude" },
          { key: "Rate", value: "every 20 ms — air pressure changes slowly" },
        ],
      },
      {
        label: "Magnetometer — 0x1E",
        sub: "heading reference",
        facts: [
          { key: "Read", value: "3 × 16-bit field values" },
          { key: "Rate", value: "every 10 ms" },
        ],
      },
      {
        label: "OLED display — 0x3C",
        sub: "status readout",
        facts: [
          { key: "Write", value: "framebuffer pages, ~1 KB per refresh" },
          { key: "Rate", value: "every 100 ms — and visibly slow on a 400 kHz bus" },
        ],
      },
      {
        label: "Why the bus copes",
        sub: "and when it stops coping",
        facts: [
          { key: "Pin cost", value: "2 pins for all five devices" },
          { key: "Limiting factor", value: "bus capacitance and the slowest device, not the clock rate" },
          { key: "Typical failure", value: "one target holding SDA low locks the bus; firmware must clock it free" },
        ],
      },
    ],
    moral:
      "I²C trades bandwidth for pin count. On a board where pins and traces are the scarce resource, two wires serving five chips is an enormous win. The cost is that everything shares one narrow pipe: the OLED pushing a kilobyte of framebuffer competes with an IMU that must be sampled every millisecond. On a real drone the high-rate sensor usually moves to a dedicated SPI bus, and I²C keeps the devices that can tolerate latency.",
  },

  comparison: {
    title: "I²C vs SPI vs UART",
    framing:
      "Three ways to connect chips on one board, each making a different trade. None is a replacement for the others — most boards use all three at once.",
    columns: [
      { label: "I²C", accentToken: "--color-i2c", accentHex: "#4fc4dd", emphasis: true },
      { label: "SPI", accentToken: "--color-i2c", accentHex: "#4fc4dd" },
      { label: "UART", accentToken: "--color-i2c", accentHex: "#4fc4dd" },
    ],
    rows: [
      {
        dimension: "Wires",
        cells: ["2 (SDA, SCL) + ground", "4 (SCLK, MOSI, MISO, CS) + ground", "2 (TX, RX) + ground"],
      },
      {
        dimension: "Pin cost per device",
        cells: ["Zero extra — address selects the device", "One extra CS line per device", "Point to point only"],
      },
      {
        dimension: "Devices on one bus",
        cells: ["Many — up to 112 usable addresses", "Many, but one chip-select pin each", "Two per link"],
      },
      {
        dimension: "Clock",
        cells: ["Synchronous — controller generates SCL", "Synchronous — controller generates SCLK", "Asynchronous — both sides pre-agree a baud rate"],
      },
      {
        dimension: "Typical speed",
        cells: ["100 kHz standard, 400 kHz fast, 1 MHz fast-plus, 3.4 MHz high-speed", "10–100 MHz", "9.6 kbaud to several Mbaud"],
      },
      {
        dimension: "Duplex",
        cells: ["Half duplex — one data line", "Full duplex — separate in and out lines", "Full duplex"],
      },
      {
        dimension: "Addressing",
        cells: ["Yes — 7-bit address in every transaction", "No — hardware chip-select per device", "No — the link itself is the addressing"],
      },
      {
        dimension: "Flow control",
        cells: ["ACK/NACK per byte, plus clock stretching", "None — the controller must respect device timing limits", "Optional RTS/CTS handshake"],
      },
      {
        dimension: "Electrical",
        cells: ["Open-drain, pull-up resistors, shared bus", "Push-pull, point to point per CS", "Push-pull, point to point"],
      },
      {
        dimension: "Overhead",
        cells: ["~2 bytes per register access", "~1 byte; a byte per register is common", "Framing and often a checksum per message"],
      },
      {
        dimension: "Best for",
        cells: [
          "Many slow devices: sensors, EEPROMs, real-time clocks, small displays",
          "Bandwidth-hungry devices: flash, SD cards, LCD controllers, high-rate IMUs",
          "Console output, GPS modules, Bluetooth/Wi-Fi modules, host-to-host links",
        ],
      },
      {
        dimension: "Main weakness",
        cells: [
          "Slow, and one stuck target can hold the whole bus low",
          "Pin-hungry — every device costs a CS line",
          "Point to point — no bus, no addressing",
        ],
      },
    ],
  },

  recap: {
    headline: "I²C in 20 seconds",
    points: [
      "A board-level bus, not a network protocol — it never appears in the TCP/IP stack.",
      "Two wires, SDA and SCL, both open-drain with external pull-up resistors. Nothing can drive a line high, so a collision is harmless.",
      "One controller generates the clock; up to 112 addressable targets share the same pair of wires.",
      "Every transaction is START, address + direction, data with an ACK after each byte, then STOP.",
      "A repeated START chains a register-write to a read without releasing the bus.",
      "Clock stretching lets a slow target hold the clock low so the controller waits for it.",
      "Choose it for many slow peripherals and scarce pins; choose SPI when bandwidth matters, and UART for a simple point-to-point console link.",
    ],
  },

  related: ["can", "udp"],

  references: [
    {
      label: "NXP UM10204 — I²C-bus specification and user manual",
      note: "The authoritative document, maintained by NXP. Bus timing, addressing, arbitration and clock stretching.",
    },
    {
      label: "NXP AN10216 — I²C Manual",
      note: "A practical companion covering pull-up sizing, bus capacitance and level shifting.",
    },
  ],
};
